---
version: '3.2'
services:

  redis:

    image: "redis:alpine"
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: "my_vhost"
      CELERY_BROKER_URL: "amqp://user:password@rabbitmq:5672/my-vhost"
      CELERY_RESULT_URL: "redis://redis:6379/0"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge